/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : flash1.h
**     Project     : Lora
**     Processor   : MKL26Z128VLH4
**     Component   : fsl_flash
**     Version     : Component 1.3.0, Driver 01.00, CPU db: 3.00.000
**     Repository  : KSDK 1.3.0
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-12-05, 14:57, # CodeGen: 152
**     Contents    :
**         RelocateFunction           - uint32_t RelocateFunction(uint32_t dest,uint32_t size,uint32_t src);
**         FlashInit                  - uint32_t FlashInit(PFLASH_SSD_CONFIG pSSDConfig);
**         FlashCommandSequence       - uint32_t FlashCommandSequence(PFLASH_SSD_CONFIG pSSDConfig);
**         PFlashGetProtection        - uint32_t PFlashGetProtection(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t *...
**         PFlashSetProtection        - uint32_t PFlashSetProtection(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t...
**         PFlashFacGetXAProtection   - uint32_t PFlashFacGetXAProtection(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t *...
**         PFlashFacGetSAProtection   - uint32_t PFlashFacGetSAProtection(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t *...
**         FlashGetSecurityState      - uint32_t FlashGetSecurityState(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t *...
**         FlashSecurityBypass        - uint32_t FlashSecurityBypass(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t *...
**         FlashEraseAllBlock         - uint32_t FlashEraseAllBlock(PFLASH_SSD_CONFIG...
**         FlashEraseAllBlockUnsecure - uint32_t FlashEraseAllBlockUnsecure(PFLASH_SSD_CONFIG...
**         FlashVerifyAllBlock        - uint32_t FlashVerifyAllBlock(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t...
**         FlashEraseSector           - uint32_t FlashEraseSector(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t...
**         FlashVerifySection         - uint32_t FlashVerifySection(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t...
**         FlashEraseSuspend          - uint32_t FlashEraseSuspend(PFLASH_SSD_CONFIG pSSDConfig);
**         FlashEraseResume           - uint32_t FlashEraseResume(PFLASH_SSD_CONFIG pSSDConfig);
**         FlashReadOnce              - uint32_t FlashReadOnce(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t...
**         FlashProgramOnce           - uint32_t FlashProgramOnce(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t...
**         FlashReadResource          - uint32_t FlashReadResource(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t...
**         FlashProgram               - uint32_t FlashProgram(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t dest,\uint32_t...
**         FlashProgramCheck          - uint32_t FlashProgramCheck(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t...
**         FlashCheckSum              - uint32_t FlashCheckSum(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t dest,\uint32_t...
**         FlashProgramSection        - uint32_t FlashProgramSection(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t...
**         FlashEraseBlock            - uint32_t FlashEraseBlock(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t...
**         FlashVerifyBlock           - uint32_t FlashVerifyBlock(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t...
**         EERAMGetProtection         - uint32_t EERAMGetProtection(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t *...
**         EERAMSetProtection         - uint32_t EERAMSetProtection(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t...
**         SetEEEEnable               - uint32_t SetEEEEnable(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t...
**         EEEWrite                   - uint32_t EEEWrite(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t dest,\uint32_t...
**         DEFlashPartition           - uint32_t DEFlashPartition(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t...
**         DFlashGetProtection        - uint32_t DFlashGetProtection(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t *...
**         DFlashSetProtection        - uint32_t DFlashSetProtection(PFLASH_SSD_CONFIG pSSDConfig,\uint8_t...
**         PFlashSwap                 - uint32_t PFlashSwap(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t...
**         PFlashSwapCtl              - uint32_t PFlashSwapCtl(PFLASH_SSD_CONFIG pSSDConfig,\uint32_t addr,\uint8_t...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file flash1.h
** @version 01.00
*/         
/*!
**  @addtogroup flash1_module flash1 module documentation
**  @{
*/         
#ifndef __flash1_H
#define __flash1_H
/* MODULE flash1. */
/* Include inherited beans */
#include "Cpu.h"
#include "SSD_FTFx.h"

/*! @brief User configuration structure 0 */
extern FLASH_SSD_CONFIG flash1_InitConfig0;

#endif
/* ifndef __flash1_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
